#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : vpp
Version  : 19.08.1
Release  : 9
URL      : https://github.com/FDio/vpp/archive/v19.08.1.tar.gz
Source0  : https://github.com/FDio/vpp/archive/v19.08.1.tar.gz
Summary  : Vector Packet Processing
Group    : Development/Tools
License  : Apache-2.0
Requires: vpp-bin = %{version}-%{release}
Requires: vpp-data = %{version}-%{release}
Requires: vpp-lib = %{version}-%{release}
Requires: vpp-license = %{version}-%{release}
Requires: vpp-plugins = %{version}-%{release}
Requires: PyYAML
Requires: distro
Requires: requests
BuildRequires : PyYAML
BuildRequires : boost-dev
BuildRequires : buildreq-cmake
BuildRequires : buildreq-distutils3
BuildRequires : buildreq-golang
BuildRequires : distro
BuildRequires : dpdk-dev
BuildRequires : glibc-dev
BuildRequires : gtk+-dev
BuildRequires : numactl-dev
BuildRequires : openssl-dev
BuildRequires : ply
BuildRequires : python3
BuildRequires : requests
Patch1: disable_dpdk_static_find_library.patch
Patch2: fix_libdir_install_location.patch

%description
This package provides VPP executables: vpp, vpp_api_test, vpp_json_test
vpp - the vector packet engine
vpp_api_test - vector packet engine API test tool
vpp_json_test - vector packet engine JSON test tool

%package bin
Summary: bin components for the vpp package.
Group: Binaries
Requires: vpp-data = %{version}-%{release}
Requires: vpp-license = %{version}-%{release}

%description bin
bin components for the vpp package.


%package data
Summary: data components for the vpp package.
Group: Data

%description data
data components for the vpp package.


%package dev
Summary: dev components for the vpp package.
Group: Development
Requires: vpp-lib = %{version}-%{release}
Requires: vpp-bin = %{version}-%{release}
Requires: vpp-data = %{version}-%{release}
Provides: vpp-devel = %{version}-%{release}
Requires: vpp = %{version}-%{release}

%description dev
dev components for the vpp package.


%package doc
Summary: doc components for the vpp package.
Group: Documentation

%description doc
doc components for the vpp package.


%package lib
Summary: lib components for the vpp package.
Group: Libraries
Requires: vpp-data = %{version}-%{release}
Requires: vpp-license = %{version}-%{release}

%description lib
lib components for the vpp package.


%package license
Summary: license components for the vpp package.
Group: Default

%description license
license components for the vpp package.


%package plugins
Summary: plugins components for the vpp package.
Group: Default

%description plugins
plugins components for the vpp package.


%prep
%setup -q -n vpp-19.08.1
cd %{_builddir}/vpp-19.08.1
%patch1 -p1
%patch2 -p1

%build
## build_prepend content
sed -i 's|${VPP_VERSION}|%{version}|' src/CMakeLists.txt
for f in vapi_c_gen.py vapi_cpp_gen.py vapi_json_parser.py; do \
sed -i 's|python2|python|' src/vpp-api/vapi/$f; \
2to3-3.8 -w src/vpp-api/vapi/$f; \
done
## build_prepend end
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1576003342
pushd src
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%cmake .. -DDPDK_INCLUDE_DIR=/usr/include/dpdk -DDPDK_SHLIB=/usr/lib64 -DCMAKE_INSTALL_LIBDIR=lib64
make  %{?_smp_mflags}  VERBOSE=1
popd
popd

%install
export SOURCE_DATE_EPOCH=1576003342
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/vpp
cp %{_builddir}/vpp-19.08.1/LICENSE %{buildroot}/usr/share/package-licenses/vpp/1128f8f91104ba9ef98d37eea6523a888dcfa5de
cp %{_builddir}/vpp-19.08.1/extras/vpp_config/LICENSE.txt %{buildroot}/usr/share/package-licenses/vpp/669a1e53b9dd9df3474300d3d959bb85bad75945
cp %{_builddir}/vpp-19.08.1/src/pkg/debian/copyright %{buildroot}/usr/share/package-licenses/vpp/ce6f4e9522a351c40cd0400eb7823207731f4421
cp %{_builddir}/vpp-19.08.1/src/vpp-api/python/LICENSE.txt %{buildroot}/usr/share/package-licenses/vpp/669a1e53b9dd9df3474300d3d959bb85bad75945
pushd src
pushd clr-build
%make_install
popd
popd
## install_append content
mkdir -p %{buildroot}/usr/share/doc/vpp
mv %{buildroot}/usr/etc/vpp/startup.conf %{buildroot}/usr/share/doc/vpp/
mv %{buildroot}/usr/etc/sysctl.d/80-vpp.conf %{buildroot}/usr/share/doc/vpp/sysctl.d-example-80-vpp.conf
## install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/elftool
/usr/bin/svmdbtool
/usr/bin/svmtool
/usr/bin/vpp
/usr/bin/vpp_api_test
/usr/bin/vpp_get_metrics
/usr/bin/vpp_get_stats
/usr/bin/vpp_prometheus_export
/usr/bin/vpp_restart
/usr/bin/vppapigen
/usr/bin/vppctl

%files data
%defattr(-,root,root,-)
/usr/share/vpp/api/core/af_packet.api.json
/usr/share/vpp/api/core/bfd.api.json
/usr/share/vpp/api/core/bier.api.json
/usr/share/vpp/api/core/bond.api.json
/usr/share/vpp/api/core/classify.api.json
/usr/share/vpp/api/core/cop.api.json
/usr/share/vpp/api/core/dhcp.api.json
/usr/share/vpp/api/core/dhcp6_ia_na_client_cp.api.json
/usr/share/vpp/api/core/dhcp6_pd_client_cp.api.json
/usr/share/vpp/api/core/ethernet_types.api.json
/usr/share/vpp/api/core/feature.api.json
/usr/share/vpp/api/core/fib_types.api.json
/usr/share/vpp/api/core/geneve.api.json
/usr/share/vpp/api/core/gre.api.json
/usr/share/vpp/api/core/interface.api.json
/usr/share/vpp/api/core/interface_types.api.json
/usr/share/vpp/api/core/ip.api.json
/usr/share/vpp/api/core/ip_types.api.json
/usr/share/vpp/api/core/ipfix_export.api.json
/usr/share/vpp/api/core/ipip.api.json
/usr/share/vpp/api/core/ipsec.api.json
/usr/share/vpp/api/core/l2.api.json
/usr/share/vpp/api/core/l2tp.api.json
/usr/share/vpp/api/core/lisp.api.json
/usr/share/vpp/api/core/lisp_gpe.api.json
/usr/share/vpp/api/core/lldp.api.json
/usr/share/vpp/api/core/memclnt.api.json
/usr/share/vpp/api/core/mfib_types.api.json
/usr/share/vpp/api/core/mpls.api.json
/usr/share/vpp/api/core/netmap.api.json
/usr/share/vpp/api/core/one.api.json
/usr/share/vpp/api/core/p2p_ethernet.api.json
/usr/share/vpp/api/core/pg.api.json
/usr/share/vpp/api/core/pipe.api.json
/usr/share/vpp/api/core/policer.api.json
/usr/share/vpp/api/core/punt.api.json
/usr/share/vpp/api/core/qos.api.json
/usr/share/vpp/api/core/rd_cp.api.json
/usr/share/vpp/api/core/session.api.json
/usr/share/vpp/api/core/span.api.json
/usr/share/vpp/api/core/sr.api.json
/usr/share/vpp/api/core/sr_mpls.api.json
/usr/share/vpp/api/core/syslog.api.json
/usr/share/vpp/api/core/tapv2.api.json
/usr/share/vpp/api/core/tcp.api.json
/usr/share/vpp/api/core/udp.api.json
/usr/share/vpp/api/core/vhost_user.api.json
/usr/share/vpp/api/core/virtio.api.json
/usr/share/vpp/api/core/vpe.api.json
/usr/share/vpp/api/core/vpe_types.api.json
/usr/share/vpp/api/core/vxlan.api.json
/usr/share/vpp/api/core/vxlan_gbp.api.json
/usr/share/vpp/api/core/vxlan_gpe.api.json
/usr/share/vpp/api/plugins/abf.api.json
/usr/share/vpp/api/plugins/acl.api.json
/usr/share/vpp/api/plugins/avf.api.json
/usr/share/vpp/api/plugins/cdp.api.json
/usr/share/vpp/api/plugins/ct6.api.json
/usr/share/vpp/api/plugins/dns.api.json
/usr/share/vpp/api/plugins/flowprobe.api.json
/usr/share/vpp/api/plugins/gbp.api.json
/usr/share/vpp/api/plugins/gtpu.api.json
/usr/share/vpp/api/plugins/http_static.api.json
/usr/share/vpp/api/plugins/igmp.api.json
/usr/share/vpp/api/plugins/ikev2.api.json
/usr/share/vpp/api/plugins/ioam_cache.api.json
/usr/share/vpp/api/plugins/ioam_export.api.json
/usr/share/vpp/api/plugins/ioam_vxlan_gpe.api.json
/usr/share/vpp/api/plugins/l2e.api.json
/usr/share/vpp/api/plugins/l3xc.api.json
/usr/share/vpp/api/plugins/lacp.api.json
/usr/share/vpp/api/plugins/lb.api.json
/usr/share/vpp/api/plugins/lb_types.api.json
/usr/share/vpp/api/plugins/mactime.api.json
/usr/share/vpp/api/plugins/map.api.json
/usr/share/vpp/api/plugins/memif.api.json
/usr/share/vpp/api/plugins/nat.api.json
/usr/share/vpp/api/plugins/nsh.api.json
/usr/share/vpp/api/plugins/nsim.api.json
/usr/share/vpp/api/plugins/oddbuf.api.json
/usr/share/vpp/api/plugins/pot.api.json
/usr/share/vpp/api/plugins/pppoe.api.json
/usr/share/vpp/api/plugins/sctp.api.json
/usr/share/vpp/api/plugins/stn.api.json
/usr/share/vpp/api/plugins/svs.api.json
/usr/share/vpp/api/plugins/trace.api.json
/usr/share/vpp/api/plugins/udp_ping.api.json
/usr/share/vpp/api/plugins/vmxnet3.api.json
/usr/share/vpp/api/plugins/vxlan_gpe_ioam_export.api.json
/usr/share/vpp/generate_json.py
/usr/share/vpp/vapi_c_gen.py
/usr/share/vpp/vapi_cpp_gen.py
/usr/share/vpp/vapi_json_parser.py
/usr/share/vpp/vppapigen_c.py
/usr/share/vpp/vppapigen_json.py

%files dev
%defattr(-,root,root,-)
/usr/include/svm/fifo_segment.h
/usr/include/svm/message_queue.h
/usr/include/svm/queue.h
/usr/include/svm/ssvm.h
/usr/include/svm/svm.h
/usr/include/svm/svm_common.h
/usr/include/svm/svm_fifo.h
/usr/include/svm/svmdb.h
/usr/include/vapi/abf.api.vapi.h
/usr/include/vapi/abf.api.vapi.hpp
/usr/include/vapi/acl.api.vapi.h
/usr/include/vapi/acl.api.vapi.hpp
/usr/include/vapi/af_packet.api.vapi.h
/usr/include/vapi/af_packet.api.vapi.hpp
/usr/include/vapi/avf.api.vapi.h
/usr/include/vapi/avf.api.vapi.hpp
/usr/include/vapi/bfd.api.vapi.h
/usr/include/vapi/bfd.api.vapi.hpp
/usr/include/vapi/bier.api.vapi.h
/usr/include/vapi/bier.api.vapi.hpp
/usr/include/vapi/bond.api.vapi.h
/usr/include/vapi/bond.api.vapi.hpp
/usr/include/vapi/cdp.api.vapi.h
/usr/include/vapi/cdp.api.vapi.hpp
/usr/include/vapi/classify.api.vapi.h
/usr/include/vapi/classify.api.vapi.hpp
/usr/include/vapi/cop.api.vapi.h
/usr/include/vapi/cop.api.vapi.hpp
/usr/include/vapi/ct6.api.vapi.h
/usr/include/vapi/ct6.api.vapi.hpp
/usr/include/vapi/dhcp.api.vapi.h
/usr/include/vapi/dhcp.api.vapi.hpp
/usr/include/vapi/dhcp6_ia_na_client_cp.api.vapi.h
/usr/include/vapi/dhcp6_ia_na_client_cp.api.vapi.hpp
/usr/include/vapi/dhcp6_pd_client_cp.api.vapi.h
/usr/include/vapi/dhcp6_pd_client_cp.api.vapi.hpp
/usr/include/vapi/dns.api.vapi.h
/usr/include/vapi/dns.api.vapi.hpp
/usr/include/vapi/ethernet_types.api.vapi.h
/usr/include/vapi/ethernet_types.api.vapi.hpp
/usr/include/vapi/feature.api.vapi.h
/usr/include/vapi/feature.api.vapi.hpp
/usr/include/vapi/fib_types.api.vapi.h
/usr/include/vapi/fib_types.api.vapi.hpp
/usr/include/vapi/flowprobe.api.vapi.h
/usr/include/vapi/flowprobe.api.vapi.hpp
/usr/include/vapi/gbp.api.vapi.h
/usr/include/vapi/gbp.api.vapi.hpp
/usr/include/vapi/geneve.api.vapi.h
/usr/include/vapi/geneve.api.vapi.hpp
/usr/include/vapi/gre.api.vapi.h
/usr/include/vapi/gre.api.vapi.hpp
/usr/include/vapi/gtpu.api.vapi.h
/usr/include/vapi/gtpu.api.vapi.hpp
/usr/include/vapi/http_static.api.vapi.h
/usr/include/vapi/http_static.api.vapi.hpp
/usr/include/vapi/igmp.api.vapi.h
/usr/include/vapi/igmp.api.vapi.hpp
/usr/include/vapi/ikev2.api.vapi.h
/usr/include/vapi/ikev2.api.vapi.hpp
/usr/include/vapi/interface.api.vapi.h
/usr/include/vapi/interface.api.vapi.hpp
/usr/include/vapi/interface_types.api.vapi.h
/usr/include/vapi/interface_types.api.vapi.hpp
/usr/include/vapi/ioam_cache.api.vapi.h
/usr/include/vapi/ioam_cache.api.vapi.hpp
/usr/include/vapi/ioam_export.api.vapi.h
/usr/include/vapi/ioam_export.api.vapi.hpp
/usr/include/vapi/ioam_vxlan_gpe.api.vapi.h
/usr/include/vapi/ioam_vxlan_gpe.api.vapi.hpp
/usr/include/vapi/ip.api.vapi.h
/usr/include/vapi/ip.api.vapi.hpp
/usr/include/vapi/ip_types.api.vapi.h
/usr/include/vapi/ip_types.api.vapi.hpp
/usr/include/vapi/ipfix_export.api.vapi.h
/usr/include/vapi/ipfix_export.api.vapi.hpp
/usr/include/vapi/ipip.api.vapi.h
/usr/include/vapi/ipip.api.vapi.hpp
/usr/include/vapi/ipsec.api.vapi.h
/usr/include/vapi/ipsec.api.vapi.hpp
/usr/include/vapi/l2.api.vapi.h
/usr/include/vapi/l2.api.vapi.hpp
/usr/include/vapi/l2e.api.vapi.h
/usr/include/vapi/l2e.api.vapi.hpp
/usr/include/vapi/l2tp.api.vapi.h
/usr/include/vapi/l2tp.api.vapi.hpp
/usr/include/vapi/l3xc.api.vapi.h
/usr/include/vapi/l3xc.api.vapi.hpp
/usr/include/vapi/lacp.api.vapi.h
/usr/include/vapi/lacp.api.vapi.hpp
/usr/include/vapi/lb.api.vapi.h
/usr/include/vapi/lb.api.vapi.hpp
/usr/include/vapi/lb_types.api.vapi.h
/usr/include/vapi/lb_types.api.vapi.hpp
/usr/include/vapi/lisp.api.vapi.h
/usr/include/vapi/lisp.api.vapi.hpp
/usr/include/vapi/lisp_gpe.api.vapi.h
/usr/include/vapi/lisp_gpe.api.vapi.hpp
/usr/include/vapi/lldp.api.vapi.h
/usr/include/vapi/lldp.api.vapi.hpp
/usr/include/vapi/mactime.api.vapi.h
/usr/include/vapi/mactime.api.vapi.hpp
/usr/include/vapi/map.api.vapi.h
/usr/include/vapi/map.api.vapi.hpp
/usr/include/vapi/memclnt.api.vapi.h
/usr/include/vapi/memclnt.api.vapi.hpp
/usr/include/vapi/memif.api.vapi.h
/usr/include/vapi/memif.api.vapi.hpp
/usr/include/vapi/mfib_types.api.vapi.h
/usr/include/vapi/mfib_types.api.vapi.hpp
/usr/include/vapi/mpls.api.vapi.h
/usr/include/vapi/mpls.api.vapi.hpp
/usr/include/vapi/nat.api.vapi.h
/usr/include/vapi/nat.api.vapi.hpp
/usr/include/vapi/netmap.api.vapi.h
/usr/include/vapi/netmap.api.vapi.hpp
/usr/include/vapi/nsh.api.vapi.h
/usr/include/vapi/nsh.api.vapi.hpp
/usr/include/vapi/nsim.api.vapi.h
/usr/include/vapi/nsim.api.vapi.hpp
/usr/include/vapi/oddbuf.api.vapi.h
/usr/include/vapi/oddbuf.api.vapi.hpp
/usr/include/vapi/one.api.vapi.h
/usr/include/vapi/one.api.vapi.hpp
/usr/include/vapi/p2p_ethernet.api.vapi.h
/usr/include/vapi/p2p_ethernet.api.vapi.hpp
/usr/include/vapi/pg.api.vapi.h
/usr/include/vapi/pg.api.vapi.hpp
/usr/include/vapi/pipe.api.vapi.h
/usr/include/vapi/pipe.api.vapi.hpp
/usr/include/vapi/policer.api.vapi.h
/usr/include/vapi/policer.api.vapi.hpp
/usr/include/vapi/pot.api.vapi.h
/usr/include/vapi/pot.api.vapi.hpp
/usr/include/vapi/pppoe.api.vapi.h
/usr/include/vapi/pppoe.api.vapi.hpp
/usr/include/vapi/punt.api.vapi.h
/usr/include/vapi/punt.api.vapi.hpp
/usr/include/vapi/qos.api.vapi.h
/usr/include/vapi/qos.api.vapi.hpp
/usr/include/vapi/rd_cp.api.vapi.h
/usr/include/vapi/rd_cp.api.vapi.hpp
/usr/include/vapi/sctp.api.vapi.h
/usr/include/vapi/sctp.api.vapi.hpp
/usr/include/vapi/session.api.vapi.h
/usr/include/vapi/session.api.vapi.hpp
/usr/include/vapi/span.api.vapi.h
/usr/include/vapi/span.api.vapi.hpp
/usr/include/vapi/sr.api.vapi.h
/usr/include/vapi/sr.api.vapi.hpp
/usr/include/vapi/sr_mpls.api.vapi.h
/usr/include/vapi/sr_mpls.api.vapi.hpp
/usr/include/vapi/stn.api.vapi.h
/usr/include/vapi/stn.api.vapi.hpp
/usr/include/vapi/svs.api.vapi.h
/usr/include/vapi/svs.api.vapi.hpp
/usr/include/vapi/syslog.api.vapi.h
/usr/include/vapi/syslog.api.vapi.hpp
/usr/include/vapi/tapv2.api.vapi.h
/usr/include/vapi/tapv2.api.vapi.hpp
/usr/include/vapi/tcp.api.vapi.h
/usr/include/vapi/tcp.api.vapi.hpp
/usr/include/vapi/trace.api.vapi.h
/usr/include/vapi/trace.api.vapi.hpp
/usr/include/vapi/udp.api.vapi.h
/usr/include/vapi/udp.api.vapi.hpp
/usr/include/vapi/udp_ping.api.vapi.h
/usr/include/vapi/udp_ping.api.vapi.hpp
/usr/include/vapi/vapi.h
/usr/include/vapi/vapi.hpp
/usr/include/vapi/vapi_common.h
/usr/include/vapi/vapi_dbg.h
/usr/include/vapi/vapi_internal.h
/usr/include/vapi/vhost_user.api.vapi.h
/usr/include/vapi/vhost_user.api.vapi.hpp
/usr/include/vapi/virtio.api.vapi.h
/usr/include/vapi/virtio.api.vapi.hpp
/usr/include/vapi/vmxnet3.api.vapi.h
/usr/include/vapi/vmxnet3.api.vapi.hpp
/usr/include/vapi/vpe.api.vapi.h
/usr/include/vapi/vpe.api.vapi.hpp
/usr/include/vapi/vpe_types.api.vapi.h
/usr/include/vapi/vpe_types.api.vapi.hpp
/usr/include/vapi/vxlan.api.vapi.h
/usr/include/vapi/vxlan.api.vapi.hpp
/usr/include/vapi/vxlan_gbp.api.vapi.h
/usr/include/vapi/vxlan_gbp.api.vapi.hpp
/usr/include/vapi/vxlan_gpe.api.vapi.h
/usr/include/vapi/vxlan_gpe.api.vapi.hpp
/usr/include/vapi/vxlan_gpe_ioam_export.api.vapi.h
/usr/include/vapi/vxlan_gpe_ioam_export.api.vapi.hpp
/usr/include/vat/json_format.h
/usr/include/vat/vat.h
/usr/include/vcl/ldp.h
/usr/include/vcl/ldp_glibc_socket.h
/usr/include/vcl/ldp_socket_wrapper.h
/usr/include/vcl/vcl_locked.h
/usr/include/vcl/vppcom.h
/usr/include/vlib/buffer.h
/usr/include/vlib/buffer_funcs.h
/usr/include/vlib/buffer_node.h
/usr/include/vlib/cli.h
/usr/include/vlib/cli_funcs.h
/usr/include/vlib/config.h
/usr/include/vlib/counter.h
/usr/include/vlib/counter_types.h
/usr/include/vlib/defs.h
/usr/include/vlib/error.h
/usr/include/vlib/error_funcs.h
/usr/include/vlib/format_funcs.h
/usr/include/vlib/global_funcs.h
/usr/include/vlib/i2c.h
/usr/include/vlib/init.h
/usr/include/vlib/linux/vfio.h
/usr/include/vlib/log.h
/usr/include/vlib/main.h
/usr/include/vlib/node.h
/usr/include/vlib/node_funcs.h
/usr/include/vlib/pci/pci.h
/usr/include/vlib/pci/pci_config.h
/usr/include/vlib/physmem.h
/usr/include/vlib/physmem_funcs.h
/usr/include/vlib/punt.h
/usr/include/vlib/threads.h
/usr/include/vlib/trace.h
/usr/include/vlib/trace_funcs.h
/usr/include/vlib/unix/cj.h
/usr/include/vlib/unix/mc_socket.h
/usr/include/vlib/unix/plugin.h
/usr/include/vlib/unix/unix.h
/usr/include/vlib/vlib.h
/usr/include/vlib/vmbus/vmbus.h
/usr/include/vlibapi/api.h
/usr/include/vlibapi/api_common.h
/usr/include/vlibapi/api_helper_macros.h
/usr/include/vlibapi/api_types.h
/usr/include/vlibapi/vat_helper_macros.h
/usr/include/vlibmemory/api.h
/usr/include/vlibmemory/memclnt.api
/usr/include/vlibmemory/memclnt.api.h
/usr/include/vlibmemory/memory_api.h
/usr/include/vlibmemory/memory_client.h
/usr/include/vlibmemory/memory_shared.h
/usr/include/vlibmemory/socket_api.h
/usr/include/vlibmemory/socket_client.h
/usr/include/vlibmemory/vl_memory_api_h.h
/usr/include/vlibmemory/vl_memory_msg_enum.h
/usr/include/vnet/adj/adj.h
/usr/include/vnet/adj/adj_glean.h
/usr/include/vnet/adj/adj_midchain.h
/usr/include/vnet/adj/adj_nbr.h
/usr/include/vnet/adj/adj_nsh.h
/usr/include/vnet/adj/adj_types.h
/usr/include/vnet/adj/rewrite.h
/usr/include/vnet/api_errno.h
/usr/include/vnet/bfd/bfd.api
/usr/include/vnet/bfd/bfd.api.h
/usr/include/vnet/bfd/bfd_api.h
/usr/include/vnet/bfd/bfd_main.h
/usr/include/vnet/bfd/bfd_protocol.h
/usr/include/vnet/bfd/bfd_udp.h
/usr/include/vnet/bier/bier.api
/usr/include/vnet/bier/bier.api.h
/usr/include/vnet/bier/bier_entry.h
/usr/include/vnet/bier/bier_table.h
/usr/include/vnet/bier/bier_types.h
/usr/include/vnet/bier/bier_update.h
/usr/include/vnet/bonding/bond.api
/usr/include/vnet/bonding/bond.api.h
/usr/include/vnet/bonding/node.h
/usr/include/vnet/buffer.h
/usr/include/vnet/classify/classify.api
/usr/include/vnet/classify/classify.api.h
/usr/include/vnet/classify/flow_classify.h
/usr/include/vnet/classify/in_out_acl.h
/usr/include/vnet/classify/policer_classify.h
/usr/include/vnet/classify/vnet_classify.h
/usr/include/vnet/config.h
/usr/include/vnet/cop/cop.api
/usr/include/vnet/cop/cop.api.h
/usr/include/vnet/cop/cop.h
/usr/include/vnet/crypto/crypto.h
/usr/include/vnet/devices/af_packet/af_packet.api
/usr/include/vnet/devices/af_packet/af_packet.api.h
/usr/include/vnet/devices/af_packet/af_packet.h
/usr/include/vnet/devices/devices.h
/usr/include/vnet/devices/netlink.h
/usr/include/vnet/devices/netmap/netmap.api
/usr/include/vnet/devices/netmap/netmap.api.h
/usr/include/vnet/devices/netmap/netmap.h
/usr/include/vnet/devices/pipe/pipe.api
/usr/include/vnet/devices/pipe/pipe.api.h
/usr/include/vnet/devices/pipe/pipe.h
/usr/include/vnet/devices/tap/tap.h
/usr/include/vnet/devices/tap/tapv2.api
/usr/include/vnet/devices/tap/tapv2.api.h
/usr/include/vnet/devices/virtio/pci.h
/usr/include/vnet/devices/virtio/vhost_user.api
/usr/include/vnet/devices/virtio/vhost_user.api.h
/usr/include/vnet/devices/virtio/vhost_user.h
/usr/include/vnet/devices/virtio/virtio.api
/usr/include/vnet/devices/virtio/virtio.api.h
/usr/include/vnet/devices/virtio/virtio.h
/usr/include/vnet/dhcp/client.h
/usr/include/vnet/dhcp/dhcp.api
/usr/include/vnet/dhcp/dhcp.api.h
/usr/include/vnet/dhcp/dhcp4_packet.h
/usr/include/vnet/dhcp/dhcp4_proxy_error.def
/usr/include/vnet/dhcp/dhcp6_client_common_dp.h
/usr/include/vnet/dhcp/dhcp6_ia_na_client_cp.api
/usr/include/vnet/dhcp/dhcp6_ia_na_client_cp.api.h
/usr/include/vnet/dhcp/dhcp6_ia_na_client_dp.h
/usr/include/vnet/dhcp/dhcp6_packet.h
/usr/include/vnet/dhcp/dhcp6_pd_client_cp.api
/usr/include/vnet/dhcp/dhcp6_pd_client_cp.api.h
/usr/include/vnet/dhcp/dhcp6_pd_client_dp.h
/usr/include/vnet/dhcp/dhcp6_proxy_error.def
/usr/include/vnet/dhcp/dhcp_proxy.h
/usr/include/vnet/dpo/classify_dpo.h
/usr/include/vnet/dpo/dpo.h
/usr/include/vnet/dpo/drop_dpo.h
/usr/include/vnet/dpo/ip_null_dpo.h
/usr/include/vnet/dpo/load_balance.h
/usr/include/vnet/dpo/lookup_dpo.h
/usr/include/vnet/dpo/punt_dpo.h
/usr/include/vnet/dpo/receive_dpo.h
/usr/include/vnet/dpo/replicate_dpo.h
/usr/include/vnet/ethernet/arp.h
/usr/include/vnet/ethernet/arp_packet.h
/usr/include/vnet/ethernet/error.def
/usr/include/vnet/ethernet/ethernet.h
/usr/include/vnet/ethernet/ethernet_types.api
/usr/include/vnet/ethernet/ethernet_types.api.h
/usr/include/vnet/ethernet/mac_address.h
/usr/include/vnet/ethernet/p2p_ethernet.api
/usr/include/vnet/ethernet/p2p_ethernet.api.h
/usr/include/vnet/ethernet/p2p_ethernet.h
/usr/include/vnet/ethernet/packet.h
/usr/include/vnet/ethernet/sfp.h
/usr/include/vnet/ethernet/types.def
/usr/include/vnet/feature/feature.api
/usr/include/vnet/feature/feature.api.h
/usr/include/vnet/feature/feature.h
/usr/include/vnet/fib/fib.h
/usr/include/vnet/fib/fib_api.h
/usr/include/vnet/fib/fib_entry.h
/usr/include/vnet/fib/fib_entry_delegate.h
/usr/include/vnet/fib/fib_node.h
/usr/include/vnet/fib/fib_node_list.h
/usr/include/vnet/fib/fib_table.h
/usr/include/vnet/fib/fib_types.api
/usr/include/vnet/fib/fib_types.api.h
/usr/include/vnet/fib/fib_types.h
/usr/include/vnet/fib/ip4_fib.h
/usr/include/vnet/fib/ip6_fib.h
/usr/include/vnet/flow/flow.h
/usr/include/vnet/geneve/geneve.api
/usr/include/vnet/geneve/geneve.api.h
/usr/include/vnet/geneve/geneve.h
/usr/include/vnet/geneve/geneve_error.def
/usr/include/vnet/geneve/geneve_packet.h
/usr/include/vnet/global_funcs.h
/usr/include/vnet/gre/error.def
/usr/include/vnet/gre/gre.api
/usr/include/vnet/gre/gre.api.h
/usr/include/vnet/gre/gre.h
/usr/include/vnet/gre/packet.h
/usr/include/vnet/handoff.h
/usr/include/vnet/hdlc/error.def
/usr/include/vnet/hdlc/hdlc.h
/usr/include/vnet/hdlc/packet.h
/usr/include/vnet/interface.api
/usr/include/vnet/interface.api.h
/usr/include/vnet/interface.h
/usr/include/vnet/interface_funcs.h
/usr/include/vnet/interface_types.api
/usr/include/vnet/interface_types.api.h
/usr/include/vnet/ip/format.h
/usr/include/vnet/ip/icmp4.h
/usr/include/vnet/ip/icmp46_packet.h
/usr/include/vnet/ip/icmp6.h
/usr/include/vnet/ip/igmp_packet.h
/usr/include/vnet/ip/ip.api
/usr/include/vnet/ip/ip.api.h
/usr/include/vnet/ip/ip.h
/usr/include/vnet/ip/ip4.h
/usr/include/vnet/ip/ip4_error.h
/usr/include/vnet/ip/ip4_mtrie.h
/usr/include/vnet/ip/ip4_packet.h
/usr/include/vnet/ip/ip4_to_ip6.h
/usr/include/vnet/ip/ip6.h
/usr/include/vnet/ip/ip6_error.h
/usr/include/vnet/ip/ip6_hop_by_hop.h
/usr/include/vnet/ip/ip6_hop_by_hop_packet.h
/usr/include/vnet/ip/ip6_neighbor.h
/usr/include/vnet/ip/ip6_packet.h
/usr/include/vnet/ip/ip6_to_ip4.h
/usr/include/vnet/ip/ip_neighbor.h
/usr/include/vnet/ip/ip_packet.h
/usr/include/vnet/ip/ip_source_and_port_range_check.h
/usr/include/vnet/ip/ip_types.api
/usr/include/vnet/ip/ip_types.api.h
/usr/include/vnet/ip/ip_types_api.h
/usr/include/vnet/ip/lookup.h
/usr/include/vnet/ip/ports.def
/usr/include/vnet/ip/protocols.def
/usr/include/vnet/ip/punt.api
/usr/include/vnet/ip/punt.api.h
/usr/include/vnet/ip/punt.h
/usr/include/vnet/ip/punt_error.def
/usr/include/vnet/ip/rd_cp.api
/usr/include/vnet/ip/rd_cp.api.h
/usr/include/vnet/ipfix-export/flow_report.h
/usr/include/vnet/ipfix-export/flow_report_classify.h
/usr/include/vnet/ipfix-export/ipfix_export.api
/usr/include/vnet/ipfix-export/ipfix_export.api.h
/usr/include/vnet/ipfix-export/ipfix_info_elements.h
/usr/include/vnet/ipfix-export/ipfix_packet.h
/usr/include/vnet/ipip/ipip.api
/usr/include/vnet/ipip/ipip.api.h
/usr/include/vnet/ipip/ipip.h
/usr/include/vnet/ipsec/ah.h
/usr/include/vnet/ipsec/esp.h
/usr/include/vnet/ipsec/ipsec.api
/usr/include/vnet/ipsec/ipsec.api.h
/usr/include/vnet/ipsec/ipsec.h
/usr/include/vnet/ipsec/ipsec_if.h
/usr/include/vnet/ipsec/ipsec_punt.h
/usr/include/vnet/ipsec/ipsec_sa.h
/usr/include/vnet/ipsec/ipsec_spd.h
/usr/include/vnet/ipsec/ipsec_spd_policy.h
/usr/include/vnet/l2/feat_bitmap.h
/usr/include/vnet/l2/l2.api
/usr/include/vnet/l2/l2.api.h
/usr/include/vnet/l2/l2_bd.h
/usr/include/vnet/l2/l2_bvi.h
/usr/include/vnet/l2/l2_classify.h
/usr/include/vnet/l2/l2_efp_filter.h
/usr/include/vnet/l2/l2_fib.h
/usr/include/vnet/l2/l2_flood.h
/usr/include/vnet/l2/l2_fwd.h
/usr/include/vnet/l2/l2_input.h
/usr/include/vnet/l2/l2_input_vtr.h
/usr/include/vnet/l2/l2_output.h
/usr/include/vnet/l2/l2_rw.h
/usr/include/vnet/l2/l2_vtr.h
/usr/include/vnet/l2/l2_xcrw.h
/usr/include/vnet/l2tp/l2tp.api
/usr/include/vnet/l2tp/l2tp.api.h
/usr/include/vnet/l2tp/l2tp.h
/usr/include/vnet/l2tp/packet.h
/usr/include/vnet/l3_types.h
/usr/include/vnet/lawful-intercept/lawful_intercept.h
/usr/include/vnet/lisp-cp/control.h
/usr/include/vnet/lisp-cp/gid_dictionary.h
/usr/include/vnet/lisp-cp/lisp.api
/usr/include/vnet/lisp-cp/lisp.api.h
/usr/include/vnet/lisp-cp/lisp_cp_messages.h
/usr/include/vnet/lisp-cp/lisp_msg_serdes.h
/usr/include/vnet/lisp-cp/lisp_types.h
/usr/include/vnet/lisp-cp/one.api
/usr/include/vnet/lisp-cp/one.api.h
/usr/include/vnet/lisp-cp/packets.h
/usr/include/vnet/lisp-gpe/lisp_gpe.api
/usr/include/vnet/lisp-gpe/lisp_gpe.api.h
/usr/include/vnet/lisp-gpe/lisp_gpe.h
/usr/include/vnet/lisp-gpe/lisp_gpe_error.def
/usr/include/vnet/lisp-gpe/lisp_gpe_fwd_entry.h
/usr/include/vnet/lisp-gpe/lisp_gpe_packet.h
/usr/include/vnet/lisp-gpe/lisp_gpe_tenant.h
/usr/include/vnet/llc/llc.h
/usr/include/vnet/lldp/lldp.api
/usr/include/vnet/lldp/lldp.api.h
/usr/include/vnet/lldp/lldp.h
/usr/include/vnet/lldp/lldp_protocol.h
/usr/include/vnet/mfib/ip4_mfib.h
/usr/include/vnet/mfib/mfib_table.h
/usr/include/vnet/mfib/mfib_types.api
/usr/include/vnet/mfib/mfib_types.api.h
/usr/include/vnet/mfib/mfib_types.h
/usr/include/vnet/mpls/error.def
/usr/include/vnet/mpls/mpls.api
/usr/include/vnet/mpls/mpls.api.h
/usr/include/vnet/mpls/mpls.h
/usr/include/vnet/mpls/mpls_tunnel.h
/usr/include/vnet/mpls/mpls_types.h
/usr/include/vnet/mpls/packet.h
/usr/include/vnet/osi/osi.h
/usr/include/vnet/pg/edit.h
/usr/include/vnet/pg/pg.api
/usr/include/vnet/pg/pg.api.h
/usr/include/vnet/pg/pg.h
/usr/include/vnet/pipeline.h
/usr/include/vnet/plugin/plugin.h
/usr/include/vnet/policer/police.h
/usr/include/vnet/policer/policer.api
/usr/include/vnet/policer/policer.api.h
/usr/include/vnet/policer/policer.h
/usr/include/vnet/policer/xlate.h
/usr/include/vnet/ppp/error.def
/usr/include/vnet/ppp/packet.h
/usr/include/vnet/ppp/ppp.h
/usr/include/vnet/qos/qos.api
/usr/include/vnet/qos/qos.api.h
/usr/include/vnet/session/application.h
/usr/include/vnet/session/application_interface.h
/usr/include/vnet/session/application_local.h
/usr/include/vnet/session/application_namespace.h
/usr/include/vnet/session/mma_16.h
/usr/include/vnet/session/mma_40.h
/usr/include/vnet/session/mma_template.c
/usr/include/vnet/session/mma_template.h
/usr/include/vnet/session/segment_manager.h
/usr/include/vnet/session/session.api
/usr/include/vnet/session/session.api.h
/usr/include/vnet/session/session.h
/usr/include/vnet/session/session_debug.h
/usr/include/vnet/session/session_lookup.h
/usr/include/vnet/session/session_rules_table.h
/usr/include/vnet/session/session_table.h
/usr/include/vnet/session/session_types.h
/usr/include/vnet/session/transport.h
/usr/include/vnet/session/transport_types.h
/usr/include/vnet/snap/snap.h
/usr/include/vnet/span/span.api
/usr/include/vnet/span/span.api.h
/usr/include/vnet/span/span.h
/usr/include/vnet/srmpls/sr_mpls.api
/usr/include/vnet/srmpls/sr_mpls.api.h
/usr/include/vnet/srmpls/sr_mpls.h
/usr/include/vnet/srp/packet.h
/usr/include/vnet/srp/srp.h
/usr/include/vnet/srv6/sr.api
/usr/include/vnet/srv6/sr.api.h
/usr/include/vnet/srv6/sr.h
/usr/include/vnet/srv6/sr_packet.h
/usr/include/vnet/syslog/syslog.api
/usr/include/vnet/syslog/syslog.api.h
/usr/include/vnet/syslog/syslog.h
/usr/include/vnet/syslog/syslog_udp.h
/usr/include/vnet/tcp/tcp.api
/usr/include/vnet/tcp/tcp.api.h
/usr/include/vnet/tcp/tcp.h
/usr/include/vnet/tcp/tcp_debug.h
/usr/include/vnet/tcp/tcp_error.def
/usr/include/vnet/tcp/tcp_packet.h
/usr/include/vnet/tcp/tcp_timer.h
/usr/include/vnet/tls/tls.h
/usr/include/vnet/tls/tls_test.h
/usr/include/vnet/udp/udp.api
/usr/include/vnet/udp/udp.api.h
/usr/include/vnet/udp/udp.h
/usr/include/vnet/udp/udp_error.def
/usr/include/vnet/udp/udp_packet.h
/usr/include/vnet/unix/tuntap.h
/usr/include/vnet/util/radix.h
/usr/include/vnet/util/refcount.h
/usr/include/vnet/util/throttle.h
/usr/include/vnet/vnet.h
/usr/include/vnet/vnet_all_api_h.h
/usr/include/vnet/vnet_msg_enum.h
/usr/include/vnet/vxlan-gbp/vxlan_gbp.api
/usr/include/vnet/vxlan-gbp/vxlan_gbp.api.h
/usr/include/vnet/vxlan-gbp/vxlan_gbp.h
/usr/include/vnet/vxlan-gbp/vxlan_gbp_error.def
/usr/include/vnet/vxlan-gbp/vxlan_gbp_packet.h
/usr/include/vnet/vxlan-gpe/vxlan_gpe.api
/usr/include/vnet/vxlan-gpe/vxlan_gpe.api.h
/usr/include/vnet/vxlan-gpe/vxlan_gpe.h
/usr/include/vnet/vxlan-gpe/vxlan_gpe_error.def
/usr/include/vnet/vxlan-gpe/vxlan_gpe_packet.h
/usr/include/vnet/vxlan/vxlan.api
/usr/include/vnet/vxlan/vxlan.api.h
/usr/include/vnet/vxlan/vxlan.h
/usr/include/vnet/vxlan/vxlan_error.def
/usr/include/vnet/vxlan/vxlan_packet.h
/usr/include/vpp-api/client/stat_client.h
/usr/include/vpp-api/client/vppapiclient.h
/usr/include/vpp/api/vpe.api.h
/usr/include/vpp/api/vpe_all_api_h.h
/usr/include/vpp/api/vpe_msg_enum.h
/usr/include/vpp/api/vpe_types.api.h
/usr/include/vpp/stats/stat_segment.h
/usr/include/vpp_plugins/abf/abf.api.h
/usr/include/vpp_plugins/abf/abf_all_api_h.h
/usr/include/vpp_plugins/abf/abf_msg_enum.h
/usr/include/vpp_plugins/acl/acl.api.h
/usr/include/vpp_plugins/acl/acl_all_api_h.h
/usr/include/vpp_plugins/acl/acl_msg_enum.h
/usr/include/vpp_plugins/acl/manual_fns.h
/usr/include/vpp_plugins/avf/avf.api.h
/usr/include/vpp_plugins/avf/avf_all_api_h.h
/usr/include/vpp_plugins/avf/avf_msg_enum.h
/usr/include/vpp_plugins/cdp/cdp.api.h
/usr/include/vpp_plugins/cdp/cdp.h
/usr/include/vpp_plugins/cdp/cdp_all_api_h.h
/usr/include/vpp_plugins/cdp/cdp_msg_enum.h
/usr/include/vpp_plugins/cdp/cdp_protocol.h
/usr/include/vpp_plugins/ct6/ct6.api.h
/usr/include/vpp_plugins/ct6/ct6_all_api_h.h
/usr/include/vpp_plugins/ct6/ct6_msg_enum.h
/usr/include/vpp_plugins/dns/dns.api.h
/usr/include/vpp_plugins/dns/dns_all_api_h.h
/usr/include/vpp_plugins/dns/dns_msg_enum.h
/usr/include/vpp_plugins/dns/dns_packet.h
/usr/include/vpp_plugins/dpdk/device/dpdk.h
/usr/include/vpp_plugins/dpdk/ipsec/ipsec.h
/usr/include/vpp_plugins/flowprobe/flowprobe.api.h
/usr/include/vpp_plugins/flowprobe/flowprobe_all_api_h.h
/usr/include/vpp_plugins/flowprobe/flowprobe_msg_enum.h
/usr/include/vpp_plugins/gbp/gbp.api.h
/usr/include/vpp_plugins/gbp/gbp.h
/usr/include/vpp_plugins/gbp/gbp_all_api_h.h
/usr/include/vpp_plugins/gbp/gbp_api_print.h
/usr/include/vpp_plugins/gbp/gbp_msg_enum.h
/usr/include/vpp_plugins/gtpu/gtpu.api.h
/usr/include/vpp_plugins/gtpu/gtpu_all_api_h.h
/usr/include/vpp_plugins/gtpu/gtpu_msg_enum.h
/usr/include/vpp_plugins/http_static/http_static.api.h
/usr/include/vpp_plugins/http_static/http_static_all_api_h.h
/usr/include/vpp_plugins/http_static/http_static_msg_enum.h
/usr/include/vpp_plugins/igmp/igmp.api.h
/usr/include/vpp_plugins/igmp/igmp_all_api_h.h
/usr/include/vpp_plugins/igmp/igmp_msg_enum.h
/usr/include/vpp_plugins/ikev2/ikev2.api.h
/usr/include/vpp_plugins/ikev2/ikev2.h
/usr/include/vpp_plugins/ikev2/ikev2_all_api.h
/usr/include/vpp_plugins/ikev2/ikev2_msg_enum.h
/usr/include/vpp_plugins/ikev2/ikev2_priv.h
/usr/include/vpp_plugins/ila/ila.h
/usr/include/vpp_plugins/ioam/encap/ip6_ioam_e2e.h
/usr/include/vpp_plugins/ioam/encap/ip6_ioam_seqno.h
/usr/include/vpp_plugins/ioam/encap/ip6_ioam_trace.h
/usr/include/vpp_plugins/ioam/export-common/ioam_export.h
/usr/include/vpp_plugins/ioam/export-vxlan-gpe/vxlan_gpe_ioam_export.api.h
/usr/include/vpp_plugins/ioam/export-vxlan-gpe/vxlan_gpe_ioam_export_all_api_h.h
/usr/include/vpp_plugins/ioam/export-vxlan-gpe/vxlan_gpe_ioam_export_msg_enum.h
/usr/include/vpp_plugins/ioam/export/ioam_export.api.h
/usr/include/vpp_plugins/ioam/export/ioam_export_all_api_h.h
/usr/include/vpp_plugins/ioam/export/ioam_export_msg_enum.h
/usr/include/vpp_plugins/ioam/ip6/ioam_cache.api.h
/usr/include/vpp_plugins/ioam/ip6/ioam_cache_all_api_h.h
/usr/include/vpp_plugins/ioam/ip6/ioam_cache_msg_enum.h
/usr/include/vpp_plugins/ioam/lib-e2e/ioam_seqno_lib.h
/usr/include/vpp_plugins/ioam/lib-pot/math64.h
/usr/include/vpp_plugins/ioam/lib-pot/pot.api.h
/usr/include/vpp_plugins/ioam/lib-pot/pot_all_api_h.h
/usr/include/vpp_plugins/ioam/lib-pot/pot_msg_enum.h
/usr/include/vpp_plugins/ioam/lib-pot/pot_util.h
/usr/include/vpp_plugins/ioam/lib-trace/trace.api.h
/usr/include/vpp_plugins/ioam/lib-trace/trace_all_api_h.h
/usr/include/vpp_plugins/ioam/lib-trace/trace_config.h
/usr/include/vpp_plugins/ioam/lib-trace/trace_msg_enum.h
/usr/include/vpp_plugins/ioam/lib-trace/trace_util.h
/usr/include/vpp_plugins/ioam/lib-vxlan-gpe/ioam_vxlan_gpe.api.h
/usr/include/vpp_plugins/ioam/lib-vxlan-gpe/vxlan_gpe_all_api_h.h
/usr/include/vpp_plugins/ioam/lib-vxlan-gpe/vxlan_gpe_ioam.h
/usr/include/vpp_plugins/ioam/lib-vxlan-gpe/vxlan_gpe_ioam_packet.h
/usr/include/vpp_plugins/ioam/lib-vxlan-gpe/vxlan_gpe_ioam_util.h
/usr/include/vpp_plugins/ioam/lib-vxlan-gpe/vxlan_gpe_msg_enum.h
/usr/include/vpp_plugins/ioam/udp-ping/udp_ping.api.h
/usr/include/vpp_plugins/ioam/udp-ping/udp_ping.h
/usr/include/vpp_plugins/ioam/udp-ping/udp_ping_all_api_h.h
/usr/include/vpp_plugins/ioam/udp-ping/udp_ping_msg_enum.h
/usr/include/vpp_plugins/ioam/udp-ping/udp_ping_packet.h
/usr/include/vpp_plugins/ioam/udp-ping/udp_ping_util.h
/usr/include/vpp_plugins/ixge/ixge.h
/usr/include/vpp_plugins/l2e/l2e.api.h
/usr/include/vpp_plugins/l2e/l2e.h
/usr/include/vpp_plugins/l2e/l2e_all_api_h.h
/usr/include/vpp_plugins/l2e/l2e_msg_enum.h
/usr/include/vpp_plugins/l3xc/l3xc.api.h
/usr/include/vpp_plugins/l3xc/l3xc_all_api_h.h
/usr/include/vpp_plugins/l3xc/l3xc_msg_enum.h
/usr/include/vpp_plugins/lacp/lacp.api.h
/usr/include/vpp_plugins/lacp/lacp_all_api_h.h
/usr/include/vpp_plugins/lacp/lacp_msg_enum.h
/usr/include/vpp_plugins/lacp/machine.h
/usr/include/vpp_plugins/lacp/mux_machine.h
/usr/include/vpp_plugins/lacp/node.h
/usr/include/vpp_plugins/lacp/protocol.h
/usr/include/vpp_plugins/lacp/ptx_machine.h
/usr/include/vpp_plugins/lacp/rx_machine.h
/usr/include/vpp_plugins/lacp/tx_machine.h
/usr/include/vpp_plugins/lb/lb.api.h
/usr/include/vpp_plugins/lb/lb.h
/usr/include/vpp_plugins/lb/lb_types.api.h
/usr/include/vpp_plugins/lb/lbhash.h
/usr/include/vpp_plugins/lb/util.h
/usr/include/vpp_plugins/mactime/mactime.api.h
/usr/include/vpp_plugins/mactime/mactime_all_api_h.h
/usr/include/vpp_plugins/mactime/mactime_msg_enum.h
/usr/include/vpp_plugins/map/lpm.h
/usr/include/vpp_plugins/map/map.api.h
/usr/include/vpp_plugins/map/map.h
/usr/include/vpp_plugins/map/map_all_api_h.h
/usr/include/vpp_plugins/map/map_msg_enum.h
/usr/include/vpp_plugins/memif/memif.api.h
/usr/include/vpp_plugins/memif/memif.h
/usr/include/vpp_plugins/memif/memif_all_api_h.h
/usr/include/vpp_plugins/memif/memif_msg_enum.h
/usr/include/vpp_plugins/nat/nat.api.h
/usr/include/vpp_plugins/nat/nat_all_api_h.h
/usr/include/vpp_plugins/nat/nat_msg_enum.h
/usr/include/vpp_plugins/nsh/nsh.api.h
/usr/include/vpp_plugins/nsim/nsim.api.h
/usr/include/vpp_plugins/nsim/nsim_all_api_h.h
/usr/include/vpp_plugins/nsim/nsim_msg_enum.h
/usr/include/vpp_plugins/oddbuf/oddbuf.api.h
/usr/include/vpp_plugins/oddbuf/oddbuf_all_api_h.h
/usr/include/vpp_plugins/oddbuf/oddbuf_msg_enum.h
/usr/include/vpp_plugins/pppoe/pppoe.api.h
/usr/include/vpp_plugins/pppoe/pppoe_all_api_h.h
/usr/include/vpp_plugins/pppoe/pppoe_msg_enum.h
/usr/include/vpp_plugins/sctp/sctp.api.h
/usr/include/vpp_plugins/sctp/sctp.h
/usr/include/vpp_plugins/sctp/sctp_all_api_h.h
/usr/include/vpp_plugins/sctp/sctp_error.def
/usr/include/vpp_plugins/sctp/sctp_msg_enum.h
/usr/include/vpp_plugins/sctp/sctp_packet.h
/usr/include/vpp_plugins/sctp/sctp_timer.h
/usr/include/vpp_plugins/srv6ad/ad.h
/usr/include/vpp_plugins/srv6am/am.h
/usr/include/vpp_plugins/srv6as/as.h
/usr/include/vpp_plugins/stn/stn.api.h
/usr/include/vpp_plugins/stn/stn.h
/usr/include/vpp_plugins/stn/stn_all_api_h.h
/usr/include/vpp_plugins/stn/stn_msg_enum.h
/usr/include/vpp_plugins/svs/svs.api.h
/usr/include/vpp_plugins/svs/svs_all_api_h.h
/usr/include/vpp_plugins/svs/svs_msg_enum.h
/usr/include/vpp_plugins/vmxnet3/vmxnet3.api.h
/usr/include/vpp_plugins/vmxnet3/vmxnet3_all_api_h.h
/usr/include/vpp_plugins/vmxnet3/vmxnet3_msg_enum.h
/usr/include/vppinfra/atomics.h
/usr/include/vppinfra/bihash_16_8.h
/usr/include/vppinfra/bihash_24_8.h
/usr/include/vppinfra/bihash_40_8.h
/usr/include/vppinfra/bihash_48_8.h
/usr/include/vppinfra/bihash_8_8.h
/usr/include/vppinfra/bihash_template.c
/usr/include/vppinfra/bihash_template.h
/usr/include/vppinfra/bihash_vec8_8.h
/usr/include/vppinfra/bitmap.h
/usr/include/vppinfra/bitops.h
/usr/include/vppinfra/byte_order.h
/usr/include/vppinfra/cache.h
/usr/include/vppinfra/callback.h
/usr/include/vppinfra/clib.h
/usr/include/vppinfra/clib_error.h
/usr/include/vppinfra/config.h
/usr/include/vppinfra/cpu.h
/usr/include/vppinfra/crc32.h
/usr/include/vppinfra/dlist.h
/usr/include/vppinfra/dlmalloc.h
/usr/include/vppinfra/elf.h
/usr/include/vppinfra/elf_clib.h
/usr/include/vppinfra/elog.h
/usr/include/vppinfra/error.h
/usr/include/vppinfra/error_bootstrap.h
/usr/include/vppinfra/fheap.h
/usr/include/vppinfra/fifo.h
/usr/include/vppinfra/file.h
/usr/include/vppinfra/flowhash_24_16.h
/usr/include/vppinfra/flowhash_8_8.h
/usr/include/vppinfra/flowhash_template.h
/usr/include/vppinfra/format.h
/usr/include/vppinfra/graph.h
/usr/include/vppinfra/hash.h
/usr/include/vppinfra/heap.h
/usr/include/vppinfra/lb_hash_hash.h
/usr/include/vppinfra/linux/syscall.h
/usr/include/vppinfra/linux/sysfs.h
/usr/include/vppinfra/llist.h
/usr/include/vppinfra/lock.h
/usr/include/vppinfra/longjmp.h
/usr/include/vppinfra/macros.h
/usr/include/vppinfra/maplog.h
/usr/include/vppinfra/math.h
/usr/include/vppinfra/mem.h
/usr/include/vppinfra/memcpy_avx2.h
/usr/include/vppinfra/memcpy_avx512.h
/usr/include/vppinfra/memcpy_sse3.h
/usr/include/vppinfra/mhash.h
/usr/include/vppinfra/mheap.h
/usr/include/vppinfra/mheap_bootstrap.h
/usr/include/vppinfra/mpcap.h
/usr/include/vppinfra/os.h
/usr/include/vppinfra/pcap.h
/usr/include/vppinfra/pcap_funcs.h
/usr/include/vppinfra/pipeline.h
/usr/include/vppinfra/pmalloc.h
/usr/include/vppinfra/pmc.h
/usr/include/vppinfra/pool.h
/usr/include/vppinfra/ptclosure.h
/usr/include/vppinfra/random.h
/usr/include/vppinfra/random_buffer.h
/usr/include/vppinfra/random_isaac.h
/usr/include/vppinfra/rbtree.h
/usr/include/vppinfra/serialize.h
/usr/include/vppinfra/sha2.h
/usr/include/vppinfra/slist.h
/usr/include/vppinfra/smp.h
/usr/include/vppinfra/socket.h
/usr/include/vppinfra/sparse_vec.h
/usr/include/vppinfra/string.h
/usr/include/vppinfra/time.h
/usr/include/vppinfra/time_range.h
/usr/include/vppinfra/timing_wheel.h
/usr/include/vppinfra/tw_timer_16t_1w_2048sl.h
/usr/include/vppinfra/tw_timer_16t_2w_512sl.h
/usr/include/vppinfra/tw_timer_1t_3w_1024sl_ov.h
/usr/include/vppinfra/tw_timer_2t_1w_2048sl.h
/usr/include/vppinfra/tw_timer_4t_3w_256sl.h
/usr/include/vppinfra/tw_timer_template.c
/usr/include/vppinfra/tw_timer_template.h
/usr/include/vppinfra/types.h
/usr/include/vppinfra/unix.h
/usr/include/vppinfra/valgrind.h
/usr/include/vppinfra/valloc.h
/usr/include/vppinfra/vec.h
/usr/include/vppinfra/vec_bootstrap.h
/usr/include/vppinfra/vector.h
/usr/include/vppinfra/vector_altivec.h
/usr/include/vppinfra/vector_avx2.h
/usr/include/vppinfra/vector_avx512.h
/usr/include/vppinfra/vector_funcs.h
/usr/include/vppinfra/vector_neon.h
/usr/include/vppinfra/vector_sse42.h
/usr/include/vppinfra/xxhash.h
/usr/include/vppinfra/xy.h
/usr/include/vppinfra/zvec.h
/usr/lib/cmake/vpp/VPPConfig.cmake
/usr/lib/cmake/vpp/api.cmake
/usr/lib/cmake/vpp/cpu.cmake
/usr/lib/cmake/vpp/library.cmake
/usr/lib/cmake/vpp/pack.cmake
/usr/lib/cmake/vpp/plugin.cmake
/usr/lib/libsvm.so
/usr/lib/libsvmdb.so
/usr/lib/libvapiclient.so
/usr/lib/libvatplugin.so
/usr/lib/libvcl_ldpreload.so
/usr/lib/libvlib.so
/usr/lib/libvlibmemory.so
/usr/lib/libvlibmemoryclient.so
/usr/lib/libvnet.so
/usr/lib/libvppapiclient.so
/usr/lib/libvppcom.so
/usr/lib/libvppinfra.so

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/vpp/*

%files lib
%defattr(-,root,root,-)
/usr/lib/vpp_api_test_plugins/acl_test_plugin.so
/usr/lib/vpp_api_test_plugins/avf_test_plugin.so
/usr/lib/vpp_api_test_plugins/cdp_test_plugin.so
/usr/lib/vpp_api_test_plugins/ct6_test_plugin.so
/usr/lib/vpp_api_test_plugins/dns_test_plugin.so
/usr/lib/vpp_api_test_plugins/flowprobe_test_plugin.so
/usr/lib/vpp_api_test_plugins/gtpu_test_plugin.so
/usr/lib/vpp_api_test_plugins/http_static_test_plugin.so
/usr/lib/vpp_api_test_plugins/ikev2_test_plugin.so
/usr/lib/vpp_api_test_plugins/ioam_test_plugin.so
/usr/lib/vpp_api_test_plugins/lacp_test_plugin.so
/usr/lib/vpp_api_test_plugins/lb_test_plugin.so
/usr/lib/vpp_api_test_plugins/mactime_test_plugin.so
/usr/lib/vpp_api_test_plugins/memif_test_plugin.so
/usr/lib/vpp_api_test_plugins/nat_test_plugin.so
/usr/lib/vpp_api_test_plugins/nsh_test_plugin.so
/usr/lib/vpp_api_test_plugins/nsim_test_plugin.so
/usr/lib/vpp_api_test_plugins/oddbuf_test_plugin.so
/usr/lib/vpp_api_test_plugins/pppoe_test_plugin.so
/usr/lib/vpp_api_test_plugins/stn_test_plugin.so
/usr/lib/vpp_api_test_plugins/vmxnet3_test_plugin.so
/usr/lib/vpp_plugins/abf_plugin.so
/usr/lib/vpp_plugins/acl_plugin.so
/usr/lib/vpp_plugins/avf_plugin.so
/usr/lib/vpp_plugins/cdp_plugin.so
/usr/lib/vpp_plugins/crypto_ia32_plugin.so
/usr/lib/vpp_plugins/crypto_openssl_plugin.so
/usr/lib/vpp_plugins/ct6_plugin.so
/usr/lib/vpp_plugins/dns_plugin.so
/usr/lib/vpp_plugins/dpdk_plugin.so
/usr/lib/vpp_plugins/flowprobe_plugin.so
/usr/lib/vpp_plugins/gbp_plugin.so
/usr/lib/vpp_plugins/gtpu_plugin.so
/usr/lib/vpp_plugins/hs_apps_plugin.so
/usr/lib/vpp_plugins/http_static_plugin.so
/usr/lib/vpp_plugins/igmp_plugin.so
/usr/lib/vpp_plugins/ikev2_plugin.so
/usr/lib/vpp_plugins/ila_plugin.so
/usr/lib/vpp_plugins/ioam_plugin.so
/usr/lib/vpp_plugins/ixge_plugin.so
/usr/lib/vpp_plugins/l2e_plugin.so
/usr/lib/vpp_plugins/l3xc_plugin.so
/usr/lib/vpp_plugins/lacp_plugin.so
/usr/lib/vpp_plugins/lb_plugin.so
/usr/lib/vpp_plugins/mactime_plugin.so
/usr/lib/vpp_plugins/map_plugin.so
/usr/lib/vpp_plugins/memif_plugin.so
/usr/lib/vpp_plugins/nat_plugin.so
/usr/lib/vpp_plugins/nsh_plugin.so
/usr/lib/vpp_plugins/nsim_plugin.so
/usr/lib/vpp_plugins/oddbuf_plugin.so
/usr/lib/vpp_plugins/perfmon_plugin.so
/usr/lib/vpp_plugins/pppoe_plugin.so
/usr/lib/vpp_plugins/sctp_plugin.so
/usr/lib/vpp_plugins/srv6ad_plugin.so
/usr/lib/vpp_plugins/srv6am_plugin.so
/usr/lib/vpp_plugins/srv6as_plugin.so
/usr/lib/vpp_plugins/stn_plugin.so
/usr/lib/vpp_plugins/svs_plugin.so
/usr/lib/vpp_plugins/tlsopenssl_plugin.so
/usr/lib/vpp_plugins/unittest_plugin.so
/usr/lib/vpp_plugins/vmxnet3_plugin.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/vpp/1128f8f91104ba9ef98d37eea6523a888dcfa5de
/usr/share/package-licenses/vpp/669a1e53b9dd9df3474300d3d959bb85bad75945
/usr/share/package-licenses/vpp/ce6f4e9522a351c40cd0400eb7823207731f4421

%files plugins
%defattr(-,root,root,-)
/usr/lib/libsvm.so.19.08.1
/usr/lib/libsvmdb.so.19.08.1
/usr/lib/libvapiclient.so.19.08.1
/usr/lib/libvatplugin.so.19.08.1
/usr/lib/libvcl_ldpreload.so.19.08.1
/usr/lib/libvlib.so.19.08.1
/usr/lib/libvlibmemory.so.19.08.1
/usr/lib/libvlibmemoryclient.so.19.08.1
/usr/lib/libvnet.so.19.08.1
/usr/lib/libvppapiclient.so.19.08.1
/usr/lib/libvppcom.so.19.08.1
/usr/lib/libvppinfra.so.19.08.1
